const assert=require('node:assert/strict');
const fs=require('fs'),os=require('os'),path=require('path');
const {spawnSync}=require('child_process');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'brand-dashboard-'));
for(const f of ['brand_config.js','brand_ranking.js','setup_brand.js','build_dashboard.js','media_classifier.js']) fs.copyFileSync(path.join(__dirname,f),path.join(dir,f));
const env={...process.env,NODE_PATH:path.join(__dirname,'node_modules')};
const run=(file,args=[])=>{const r=spawnSync(process.execPath,[path.join(dir,file),...args],{env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r;};
const name='演示品牌 <A&B>';
run('setup_brand.js',['--name',name]);
const cfg=require(path.join(dir,'brand_config'));
assert.equal(cfg.getBrandRank(`先了解高途，再了解${name}：课程介绍`),2);
assert.equal(cfg.getBrandRank(`介绍${name}`),1);
assert.equal(cfg.getBrandRank(`高途、高途课堂、${name}`),2);
assert.equal(cfg.getBrandRank(`| 品牌 | 说明 |\n|---|---|\n| 高途 | 简介 |\n| ${name} | 简介 |`),2);
assert.equal(cfg.getBrandRank(`## 高途\n课程介绍\n## ${name}\n课程介绍`),2);
assert.equal(cfg.getBrandRank('没有匹配'),-1);
assert.equal(cfg.isOwnReference({title:'其他机构文章'}),false);
const batchDir=path.join(cfg.DATA_ROOT,'2026-09-28','batches');fs.mkdirSync(batchDir,{recursive:true});
const base={brandName:name,platform:'doubao',question:'如果学生基础一般，希望通过线上辅导提升高中数学成绩，应该如何选择适合自己的课程和学习计划？',answerText:`高途提供课程；${name}提供课程`,shareUrl:'https://example.com/answer',references:[{title:`${name}教学介绍`,url:'https://www.zhihu.com/question/123',date:'2026-09-28'},{title:'其他机构发文标题不应出现',url:'https://example.com/other'}]};
const rows=[base,{...base,platform:'deepseek',answerText:`了解${name}`},{...base,platform:'yiyan',answerText:'无匹配'},{...base,question:'异常题',error:'timeout'},{...base,brandName:'另一个品牌',question:'其他品牌数据不应出现'}];
fs.writeFileSync(path.join(batchDir,'brand-doubao-20260928-01.json'),JSON.stringify(rows.filter(r=>r.platform==='doubao')));
for(const platform of ['deepseek','yiyan']) fs.writeFileSync(path.join(batchDir,`brand-${platform}-20260928-01.json`),JSON.stringify(rows.filter(r=>r.platform===platform)));
run('build_dashboard.js',['--date','20260928']);
const out=path.join(cfg.DATA_ROOT,'2026-09-28','dashboards','brand-dashboard-20260928.html');
const html=fs.readFileSync(out,'utf8');
for(const text of ['品牌平均顺序位次','跨平台品牌出现详情','引用媒体明细','下载XLSX','下载CSV','selMediaType','演示品牌 &lt;A&amp;B&gt;','第2名']) assert.ok(html.includes(text),text);
for(const text of ['其他品牌数据不应出现','其他机构发文标题不应出现']) assert.ok(!html.includes(text),text);
const XLSX=require('xlsx');
const encoded=html.match(/spreadsheetml.sheet;base64,([A-Za-z0-9+/=]+)/)[1];
const book=XLSX.read(Buffer.from(encoded,'base64'));
const data=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1});
assert.ok(data.flat().includes(name+'第2名'));
assert.ok(data.flat().includes(name+'第1名'));
assert.ok(data.flat().includes('采集异常'));
const media=Buffer.from(html.match(/data:text\/csv;base64,([A-Za-z0-9+/=]+)/)[1],'base64').toString('utf8');
assert.ok(media.includes('2026-09-28'));assert.ok(!media.includes('其他机构'));
run('setup_brand.js',['--name','第二品牌']);run('build_dashboard.js',['--date','20260928']);
assert.equal(fs.readdirSync(path.join(dir,'data')).length,2);
console.log('PASS: 单品牌隔离、正文顺序/表格/章节名次、原版模块、XLSX、引用筛选、CSV');
console.log('PREVIEW='+out);
